spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://configserver:8071/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lowerCaseServiceId: true
          httpclient:
           connect-timeout: 1000
           response-timeout: 2s
  data:
    redis:
      connect-timeout: 1000
      host: localhost
      port: 6379
      timeout: 1s



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true


info:
  app:
    name: "gatewayserver"
    description: "gateway server"
    version: "1.0.0"

# Logging Configuration
# Sets DEBUG level logging for the application's main package
# DEBUG level shows detailed application flow information, useful for development
# Available levels (from most to least verbose):
# TRACE > DEBUG > INFO > WARN > ERROR > FATAL
logging:
  level:
    com:
      wendyam_rayaisse:
        gatewayserver: DEBUG


# Circuit Breaker Configuration
# - Monitors last 10 calls (slidingWindowSize)
# - If 50%+ calls fail, circuit opens (failureRateThreshold: 50%)
# - After 10 seconds, allows 2 test calls (permittedNumberOfCallsInHalfOpenState)
# - If test calls succeed, circuit closes; if not, stays open for another 10 seconds
resilience4j.circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
