server:
  port: 4008

spring:
  application:
    name: "resultat-service"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3315/resultatdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled : true
  endpoint:
    health:
      probes:
        enabled: true


