apiVersion: apps/v1
kind: Deployment
metadata:
  name: rdv-service-deployment
  labels:
    app: rdv-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rdv-service
  template:
    metadata:
      labels:
        app: rdv-service
    spec:
      containers:
        - name: rdv-service
          image: rayaisse/rdv-service:v4
          ports:
            - containerPort: 4004
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: rayaisse-configmap
                  key: RDV_SERVICE_APPLICATION_NAME
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: rayaisse-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: rayaisse-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: rayaisse-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://rdvdb:3306/rdvdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "com.mysql.cj.jdbc.Driver"
            - name:  SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"




---
apiVersion: v1
kind: Service
metadata:
  name: rdv-service
spec:
  selector:
    app: rdv-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4004
      targetPort: 4004