apiVersion: v1
kind: ConfigMap
metadata:
  name: rayaisse-configmap
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
  CONFIGSERVER_APPLICATION_NAME: "configserver"
  EUREKA_APPLICATION_NAME: "eurekaserver"
  PATIENT_MYSQL_DATABASE: "patientdb"
  MEDECIN_MYSQL_DATABASE: "medecindb"
  CONSULTATION_MYSQL_DATABASE: "consultationdb"
  DISPONIBILITE_MYSQL_DATABASE: "disponibilitedb"
  CONSTANTE_MYSQL_DATABASE: "constantedb"
  RDV_MYSQL_DATABASE: "rdvdb"
  USER_MYSQL_DATABASE: "userdb"
  EXAMEN_MYSQL_DATABASE: "examendb"
  PRESCRIPTION_MYSQL_DATABASE: "prescriptiondb"
  RESULTAT_MYSQL_DATABASE: "resultatdb"
  PATIENT_SERVICE_APPLICATION_NAME: "patient-service-ms"
  MEDECIN_SERVICE_APPLICATION_NAME: "medecin-service-ms"
  PATIENT_MEDECIN_SERVICE_APPLICATION_NAME: "patient-medecin-service-ms"
  RDV_SERVICE_APPLICATION_NAME: "rdv-service-ms"
  CONSULTATION_SERVICE_APPLICATION_NAME: "consultation-service-ms"
  DISPONIBILITE_SERVICE_APPLICATION_NAME: "disponibilite-service-ms"
  CONSTANTE_SERVICE_APPLICATION_NAME: "constante-service-ms"
  USER_SERVICE_APPLICATION_NAME: "patient-medecin-ms"
  GATEWAYSERVER_APPLICATION_NAME: "gatewayserver-ms"
  KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
  KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:7080/realms/master/protocol/openid-connect/certs"