build:
  version: "1.0.0"

constante-service:
  message: "Fichier de configuration du service constante-service en local"
  contactDetails:
    name: "RAYAISSE Patrick Renaud Wendyam"
    email: "wendyam.rayaisse@gmail.com"
  onCallSupport: "+226 65 27 21 74"