build:
  version: "1.0.0"

consultation-service:
  message: "Fichier de configuration du service consultation-service pour testeur"
  contactDetails:
    name: "RAYAISSE Patrick Renaud Wendyam"
    email: "wendyam.rayaisse@gmail.com"
  onCallSupport: "+226 65 27 21 74"
