build:
  version: "1.0.0"


patient_medecin-service:
  message: "Fichier de configuration du service patient_medecin-service pour les tests"
  contactDetails:
    name: "RAYAISSE Patrick Renaud Wendyam"
    email: "wendyam.rayaisse@gmail.com"
  onCallSupport: "+226 65 27 21 74"