server:
  port: 4009

spring:
  application:
    name: "consultation-service"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3308/consultationdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

    function:
      definition: updateCommunication
    stream:
      bindings:
        sendCommunication-out-0:
          destination: send-communication
        updateCommunication-in-0:
          destination: communication-sent
          group: ${spring.application.name}

      kafka:
        binder:
          brokers:
            - localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled : true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "consultation-service"
    description: "consultation service"
    version: "1.0.0"

logging:
  level:
    com:
      wendyam_rayaisse:
        consultationservice: DEBUG

# Circuit Breaker Configuration
# - Monitors last 10 calls (slidingWindowSize)
# - If 50%+ calls fail, circuit opens (failureRateThreshold: 50%)
# - After 10 seconds, allows 2 test calls (permittedNumberOfCallsInHalfOpenState)
# - If test calls succeed, circuit closes; if not, stays open for another 10 seconds
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000


resilience4j.retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1000
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2

