server:
  port: 4000

spring:
  application:
    name: "patient-service"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3306/patientdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled : true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "patient-service"
    description: "patient service"
    version: "1.0.0"

logging:
  level:
    com:
      wendyam_rayaisse:
        patient: DEBUG

